name: Slack Approval Message
description: Sends Slack Approve/Reject message
inputs:
  slack_token:
    required: true
    description: "Slack bot token"
  channel_id:
    required: true
    description: "channel ID"
  repository:
    required: true
    description: "Repository"
  environment:
    required: true
    description: "Environemnt"
  region:
    required: true
    description: "region"
  image_tag:
    required: true
    description: "image tag"
  approval_url:
    required: true
    description: "Approval status"

runs:
  using: "node20"
  main: "index.js"
